spring:
  application:
    name: catalog-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://192.168.1.1:5435/catalog-service"
    username: postgres
    password: test