spring:
  application:
    name: catalog-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9094
  datasource:
    url: "jdbc:postgresql://localhost:5435/catalog-service"
    username: postgres
    password: test
  cloud:
    function:
      definition: orderCreatedConsumerFunction
    stream:
      bindings:
        orderCreatedConsumerFunction-in-0:
          destination: order-events
          group: catalog-service #mesaj her instance'a değil gruba bir kere gönderilsin.
          contentType: application/json
          consumer:
            max-attempts: 5
            back-off-initial-interval: 500
            back-off-max-interval: 5000
            back-off-multiplier: 2.0
      kafka:
        bindings:
          orderCreatedConsumerFunction-in-0:
            consumer:
              enable-dlq: true
              dlq-name: order-events.DLQ.catalog-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 10.10