spring:
  application:
    name: gateway.server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: catalog-service-static-route
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/products/**

server:
  port: 8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
