spring:
  application:
    name: gateway.server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: catalog-service-route
              uri: lb://catalog-service
              predicates:
                - Path=/api/v1/products/**
            - id: order-service-route
              uri: lb://order.service
              predicates:
                - Path=/api/v1/orders/**

server:
  port: 8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
