spring:
  application:
    name: eureka.server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Sunucunun kendisi, kendini tan?tmaya çal??mas?n.
    fetch-registry: false # Di?er sunucu bilgilerini çekmeye çal??ma.
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/