spring:
  application:
    name: config.server
  profiles:
    active: git, vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halitkalayci/advanced-configurations.git
          default-label: master
          search-paths: .
        vault:
          host: 127.0.0.1
          port: 8200
          scheme: http
          authentication: TOKEN
          token: ${VAULT_TOKEN:root}
          backend: secret
          order: 1
          profile-separator: /

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8787