openapi: 3.0.3

info:
  title: Catalog API
  version: 2.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: CatalogApiV2

paths:
  /api/v2/products:
    post:
      summary: This endpoint creates a new product in database if request is valid.
      operationId: createProduct
      tags:
        - ProductsV2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebProductCreateRequestV2'
            examples:
              sample:
                value:
                  name: "Klavye"
                  description: "Mekanik RGB Klavye ürünü."
                  price: 149.90
      responses:
        "201":
          description: Created Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebProductResponseV2'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseV2'
components:
  schemas:
    ErrorResponseV2:
      type: object
      required: [code,message]
      properties:
        code: {type: string}
        message: {type: string}
    WebProductResponseV2:
      type: object
      required: [ id, name, price,currency ]
      properties:
        id: { type: string, format: uuid }
        name: { type: string, minLength: 1, maxLength: 255 }
        price: { type: number, format: BigDecimal, minimum: 0 }
        description: { type: string, maxLength: 2000 }
        currency: { type: string, maxLength: 10 }
    WebProductCreateRequestV2:
      type: object
      required: [name,price,currency]
      properties:
        name:  { type: string, minLength: 1, maxLength: 255 }
        price: { type: number, format: BigDecimal, minimum: 0 }
        description: { type: string, maxLength: 2000 }
        currency: { type: string, maxLength: 10 }
