spring:
  application:
      name: order.service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5435/order-service"
    username: postgres
    password: test
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    function:
      definition: outboxPublisherSupplier
    stream:
      bindings:
        outboxPublisherSupplier-out-0:
          destination: order-events
          contentType: application/json
      kafka:
        bindings:
          outboxPublisherSupplier-out-0:
            producer:
              configuration:
                acks: all
                enable.idempotence: true
server:
  port: 8081

app:
  outbox:
    poll:
      max-attempts: 10
      interval-ms: 1000
      batch-size: 100
